== RxJava 3 API

[[_setting_up_with_an_rxified_router]]
=== 配置 Rxified 路由

若需要在 Rxified `link:../../apidocs/io/vertx/rxjava3/ext/web/Route.html[路由]` 中处理 GraphQL 请求，则请确保已导入了 `link:../../apidocs/io/vertx/rxjava3/ext/web/handler/graphql/GraphQLHandler.html[GraphQLHandler]` 类。

[[_working_with_vert_x_rxified_apis]]
=== 使用 Vert.x 的 Rxified API

GraphQL-Java 期望 DataFetcher 和批量加载器使用 `CompletionStage` 提供异步结果。

但是若您使用 Vert.x Rxified API （如 https://vertx.io/docs/vertx-web-client/java/#_rxjava_3_api[Web 客户端]），则需要适配 `Single` 和 `Maybe` 对象。

[source,java]
----
DataFetcher<CompletionStage<String>> fetcher = environment -> {
 Single<String> data = loadDataFromBackend();
 return data.toCompletionStage();
};
----

[TIP]
====
Instead of converting `Single` or `Maybe` to `CompletionStage` manually in every data fetcher implementation, configure GraphQL-Java with the `link:../../apidocs/io/vertx/rxjava3/ext/web/handler/graphql/instrumentation/SingleAdapter.html[SingleAdapter]` and `link:../../apidocs/io/vertx/rxjava3/ext/web/handler/graphql/instrumentation/MaybeAdapter.html[MaybeAdapter]` https://www.graphql-java.com/documentation/instrumentation/[instrumentations].

First, declare the instrumentations while configuring GraphQL-Java.

[source,java]
----
graphQLBuilder.instrumentation(new ChainedInstrumentation(SingleAdapter.create(), MaybeAdapter.create()));
----

Then you can return `Single` or `Maybe` directly.

[source,java]
----
DataFetcher<Single<List<Link>>> dataFetcher = environment -> {
  Single<List<Link>> single = retrieveLinksFromBackend(environment);
  return single;
};
----
====