name: Deploy

on:
  push:
    branches: [ master ]

concurrency:
  group: master-deploy
  cancel-in-progress: true

permissions:
  contents: read
  # these permissions are required for the deploy-pages action to work properly
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      # links this workflow to the deployments page on your repository
      name: github-pages
      # attaches the deployed URL to this job on the workflow summary
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Delete tools not needed for the build process
      # This saves about 4GB of disk space
      - name: Delete unnecesary tools
        run: |
          df -h /
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          df -h /

      - uses: actions/checkout@v2

      # Remove more unnecessary tools. We should have about 52GB of free disk space after this.
      # See https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh
      # NOT NEEDED AT THE MOMENT - DISK SIZE IS LARGE ENOUGH
      # RE-ENABLE LATER IF NECESSARY
      # - name: Free up more disk space
      #   run: |
      #     .github/workflows/free_disk_space.sh

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: actions/cache@v2
        with:
          path: |
            .cache
            .next/cache
            docs/compiled
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: |
          du -sh *
          df -h / /mnt

      - run: npm ci

      # Download, extract, and compile docs
      - run: npm run update-docs
      - run: |
          du -sh *
          df -h / /mnt

      # Remove files that have been used while running 'update-docs' but that
      # are not needed anymore for the remainder of the workflow. This is
      # necessary to save disk space.
      - name: Cleanup temporary files
        run: |
          rm -rf docs/download
          rm -rf docs/extracted
          rm -rf docs/node_modules
      - run: |
          du -sh *
          df -h / /mnt

      # Temporarily move apidocs out of the way
      - run: |
          mkdir .apidocs_temp
          mv public/docs/* .apidocs_temp

      # Build website
      - run: npm run build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - run: |
          du -sh *
          df -h / /mnt

      # Remove files that have been used during build but that are not needed
      # anymore for the remainder of the workflow. This is necessary to save
      # disk space.
      - name: Cleanup temporary files
        run: |
          rm -rf node_modules
      - run: |
          du -sh *
          df -h / /mnt

      - name: Prepare output directory
        run: |
          mkdir vertx-china.github.io
          cd vertx-china.github.io
          touch .nojekyll
          cd ..

      - name: Copy build to output directory
        run: |
          shopt -s dotglob                   # include dot files
          mv out/* vertx-china.github.io

      - name: Copy API docs into output directory
        run: |
          mv .apidocs_temp/apidocs vertx-china.github.io/docs/
          find .apidocs_temp -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0 -n1 -I '{}' sh -xc 'mv {}/* vertx-china.github.io/docs/$(basename {})/'
      - run: |
          du -sh *
          df -h / /mnt

      - name: Create Archive
        run: |
          cd vertx-china.github.io
          tar --dereference --hard-dereference -cf ../website.tar .

      - name: Upload Archive
        uses: actions/upload-artifact@v3
        with:
          name: Built Website
          path: website.tar
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          emit_telemetry: false # telemetry is not currently supported for custom builds
#  sync:
#    runs-on: ubuntu-latest
#    if: ${{ github.ref == 'refs/heads/master' }}
#    strategy:
#      matrix:
#        include:
#          - step: Gitee Pages
#            repo-url: git@gitee.com:vertx-china/vertx-china.git
#          - step: Coding.net
#            repo-url: git@e.coding.net:lippen/cn.vertx.tk.git
#    name: Deploy to ${{ matrix.step }}
#    needs: deploy
#    steps:
#      - name: Clone current GitHub Pages repo
#        run: git clone --depth 1 https://github.com/vertx-china/vertx-china.github.io.git
#
#      - name: Clean output directory
#        run: |
#          rm -rf vertx-china.github.io/.git
#          rm vertx-china.github.io/.nojekyll
#          rm -rf vertx-china.github.io/docs/apidocs/*
#          rm -rf vertx-china.github.io/docs/apidocs
#          rm -rf vertx-china.github.io/docs/**/apidocs/*
#
#      - name: Deploy to ${{ matrix.step }}
#        uses: actionhub/workflows/git-deploy@v1
#        with:
#          ssh-key: ${{ secrets.GITEE_TOKEN }}
#          src-dir: vertx-china.github.io
#          branch: master
#          repo-url: ${{ matrix.repo-url }}
#          user-name: okou19900722
#          user-email: 512058895@qq.com
#          commit-message: publish
#          force-orphan: true
#
#  refresh:
#    runs-on: ubuntu-latest
#    needs: sync
#    steps:
#      - name: Refresh Gitee Pages
#        uses: actionhub/gitee-pages@v1
#        with:
#          username: "okou19900722"
#          password: ${{ secrets.GITEE_PASSWORD }}
#          repository: "https://gitee.com/vertx-china/vertx-china"
#          branch: "master"
#          directory: ""
#          https: 'true'
##         env:
##           RUNNER_DEBUG: 1
