name: Node.js CI

on:
  push:
    branches: [ master ]

concurrency:
  group: master
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Delete tools not needed for the build process
      # This saves about 4GB of disk space
      - name: Delete unnecesary tools
        run: |
          df -h /
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          df -h /

      - uses: actions/checkout@v2

      # Remove more unnecessary tools. We should have about 52GB of free disk space after this.
      # See https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh
      # NOT NEEDED AT THE MOMENT - DISK SIZE IS LARGE ENOUGH
      # RE-ENABLE LATER IF NECESSARY
      # - name: Free up more disk space
      #   run: |
      #     .github/workflows/free_disk_space.sh

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: actions/cache@v2
        with:
          path: |
            .cache
            docs/compiled
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: |
          du -sh *
          df -h / /mnt

      - run: npm ci

      # Download, extract, and compile docs
      - run: npm run update-docs
      - run: |
          du -sh *
          df -h / /mnt

      # Remove files that have been used while running 'update-docs' but that
      # are not needed anymore for the remainder of the workflow. This is
      # necessary to save disk space.
      - name: Cleanup temporary files
        run: |
          rm -rf docs/download
          rm -rf docs/extracted
          rm -rf docs/node_modules
      - run: |
          du -sh *
          df -h / /mnt

      # Temporarily move apidocs out of the way
      - run: |
          mkdir .apidocs_temp
          mv public/docs/* .apidocs_temp

      # Build website
      - run: npm run build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          du -sh *
          df -h / /mnt

      # Remove files that have been used during build but that are not needed
      # anymore for the remainder of the workflow. This is necessary to save
      # disk space.
      - name: Cleanup temporary files
        run: |
          rm -rf node_modules
      - run: |
          du -sh *
          df -h / /mnt

      - name: Prepare deployment on GitHub Pages
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/github
          cat >>~/.ssh/config <<EOL
          Host github.com
            HostName github.com
            IdentityFile ~/.ssh/github
            User git
          EOL
          chmod 700 ~/.ssh
          chmod -R 600 ~/.ssh/*
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      # clone pages repo but do not checkout anything - we will recreate
      # everything from scratch anyhow
      - name: Clone current GitHub Pages repo
        run: git clone --depth 1 --no-checkout git@github.com:vertx-web-site/vertx-web-site.github.io.git
      - run: |
          du -sh *
          df -h / /mnt

      - name: Prepare output directory
        run: |
          cd vertx-web-site.github.io
          touch .nojekyll
          echo vertx.io > CNAME
          cd ..

      - name: Copy build to output directory
        run: mv out/* vertx-web-site.github.io

      - name: Copy API docs into output directory
        run: find .apidocs_temp -maxdepth 1 -type d -exec sh -c "mv {}/* vertx-web-site.github.io/docs/$(basename {})/" \;
      - run: |
          du -sh *
          df -h / /mnt

      - name: Deploy to GitHub Pages
        run: |
          cd vertx-web-site.github.io
          git add -A
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -q -m "deploy: $GITHUB_REPOSITORY@$GITHUB_SHA"
          git push origin master
          cd ..
