name: Node.js CI

on:
  push:
    branches: [ disk-space ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # put gradle user home on another volume so we have more space on /
      GRADLE_USER_HOME: /mnt/gradle

    steps:
      # Delete tools not needed for the build process
      # This saves about 4GB of disk space
      - name: Delete unnecesary tools
        run: |
          df -h /
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          df -h /

      # Prepare gradle user home
      - run: |
          sudo mkdir $GRADLE_USER_HOME
          sudo chmod uog+rwx $GRADLE_USER_HOME

      - run: |
          df -h

      - uses: actions/checkout@v2

      - run: |
          du -sh *
          df -h

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: |
          du -sh *
          df -h

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - run: |
          du -sh *
          df -h

      - uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: |
          du -sh *
          df -h

      - run: npm ci
      - run: |
          du -sh *
          df -h
      - run: npm run update-docs
      - run: |
          du -sh *
          df -h
      - run: npm run build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          du -sh *
          df -h

      # Remove files that have been used during build but that are not needed
      # anymore for the remainder of the workflow. This is necessary to save
      # disk space.
      - name: Cleanup temporary files
        run: |
          rm -rf docs/extracted
          rm -rf node_modules
          rm -rf public/docs
      - run: |
          du -sh *
          df -h

      - name: Clone current GitHub Pages repo
        run: git clone --depth 1 https://github.com/vertx-web-site/vertx-web-site.github.io.git
      - run: |
          du -sh *
          df -h

      - name: Clean output directory
        run: |
          rm -rf vertx-web-site.github.io/.git
          rm vertx-web-site.github.io/.nojekyll
      - run: |
          du -sh *
          df -h

      - name: Copy build to output directory
        run: mv out/* vertx-web-site.github.io
      - run: |
          du -sh *
          df -h

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: vertx-web-site/vertx-web-site.github.io
          publish_branch: disk-space
          publish_dir: vertx-web-site.github.io
          cname: vertx.io
      - run: |
          du -sh *
          df -h
